### ISSUE TITLE
Rewrite of observer vs. adding another observer

### ISSUE THREAD

**Issue by kirkmadera** [defactodesign/adminfirewall#1]
The admin observer is rewritten here https://github.com/defactodesign/adminfirewall/blob/master/src/app/code/community/Defacto/Adminfirewall/etc/config.xml. It could instead be a separate additional observer listening to the same event. This would be a better design pattern for a module like this which would potentially be applied across all projects globally. If we get time to make a pr, I'll send one your way.

**Comment by pocallaghan** [comment]
We initially experimented with a separate observer, but it's imperative that the code happens before the Mage_Admin observer. The only way I know of to guarantee this outside of the rewrite it to make our module a dependency of Mage_Admin. Since we can't edit the core, this means including something like the following in our own module declaration file:

``` xml
<Mage_Admin>
    <depends>
       <Defacto_Adminfirewwall />
    </depends>
</Mage_Admin>
```

We decided this is less obvious and would potentially cause more confusion than a conventional rewrite. Happy to hear your thoughts though.

**Comment by kirkmadera** [comment]
Seems fair. Thanks for the explanation. There is no way to specify priority on event observers in Magento, so I think you are correct in how it was done, given the constraints.

**Comment by punkstar** [comment]
@pocallaghan That's good to know and would probably be a good addition to the readme as it's a question I asked myself as I read through the source.

**Comment by pocallaghan** [comment]
@punkstar Good idea. I'll look to add an FAQ section to the bottom of the Readme.

**Comment by pocallaghan** [comment]
I've added a FAQ section to the README explaining this decision. Thanks for the feedback. :)
